name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Tests
        run: npm test -- --coverage --collectCoverageFrom="./app/**"
  deploy:
    name: Deploy
    runs-on: windows-latest
    needs: build
    steps:
      - name: Deploy to server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sh /home/comunidades/backend_deploy.sh
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_USER_PASSWORD }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
        
        
